name: Code Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - uses: ./.github/actions
    - name: Run tests
      run: npm run test:coverage

    - name: Upload base-json coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/base-json/coverage-final.json
        flags: base-json

    - name: Upload json coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/json/coverage-final.json
        flags: json
    
    - name: Upload json-api coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/json-api/coverage-final.json
        flags: json-api
    
    - name: Upload testing coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/testing/coverage-final.json
        flags: testing
    
    - name: Upload widgets coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/widgets/coverage-final.json
        flags: widgets
