# This workflow will run tests using node and then publish a package to npm when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: |
          npm ci
          npm install -g @angular/cli@13.3.6
          npm run build
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - name: Publish base-json
        working-directory: ./dist/base-json
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Publish json
        working-directory: ./dist/json
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Publish json-api
        working-directory: ./dist/json-api
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Publish testing
        working-directory: ./dist/testing
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Publish widgets
        working-directory: ./dist/widgets
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
